winlogbeat.event_logs:
  - name: Application
    ignore_older: 168h
  - name: Security
    ignore_older: 168h
  - name: System
    ignore_older: 168h
tags: ["winsrv"]

output.logstash:
  hosts: ["192.168.0.16:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: C:/Program Files/Winlogbeat/logs
  name: winlogbeat
  keepfiles: 7
